backend:
  name: gitlab
  repo: madebyporter/versa
  branch: master

# This line should *not* be indented
# publish_mode: editorial_workflow

# These lines should *not* be indented
public_folder: "source/twigs"
media_folder: "source/twigs/media"

display_url: https://versa.netlify.com

collections:
  - name: "twigs" # Used in routes, e.g., /admin/collections/blog
    label: "Twig" # Used in the UI
    folder: "/source/twigs/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "html.markdown"
    format: "yaml-frontmatter"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "twigs_layout"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Trunk", name: "category", widget: "string"}
      - label: "Branches"
        name: "tags"
        widget: "list"
        field: {widget: "select", options: ["UX Design", "UI Design", "Graphic Design", "Interaction Design", "Web Design"]}
      - {label: "Abstract", name: "abstract", widget: "text"}
      - label: "Links"
        name: "links"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Description", name: "desc", widget: "text"}
          - {label: "Type", name: "type", widget: "select", options: ["tools", "reference", "resources", "content"]}
          - {label: "URL", name: "url", widget: "string"}
